[package]
name = "mkfifo"
version = "0.1.0"
authors = ["gkuga"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.16.1"
tempdir = "0.3.7"
